apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    name: db-selector
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: hss
spec:
  selector:
    name: hss-selector
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mme
spec:
  selector:
    name: mme-selector
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: spgw
spec:
  selector:
    name: spgw-selector
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: enb
spec:
  selector:
    name: enb-selector
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
#apiVersion: v1
#kind: Pod
metadata:
  name: db-selector
  labels:
    name: db-selector        
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-selector
  template:
    metadata:
      labels:
        app: db-selector
    spec:       
      hostname: db
      #subdomain: db
      containers:
      - name: db
        image: cly1213/oai_db_deploy:v3
      env:
      # Use secret in real usage
      - name: MYSQL_ROOT_PASSWORD
        value: linux
      ports:
      - containerPort: 3306

    #hostNetwork: true
    #restartPolicy: Always
    #dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Pod
metadata:
  name: hss
  labels:
    name: hss-selector
spec:
  hostname: hss
  #subdomain: hss
  containers:
  - name: hss
    image: cly1213/hss:0.5
  #hostNetwork: true
  #restartPolicy: Always
  #dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Pod
metadata:
  name: mme
  labels:
    name: mme-selector

spec:
  hostname: mme
  #subdomain: mme
  containers:
  - name: mme
    image: cly1213/mme:0.5
  #hostNetwork: true
  #restartPolicy: Always
  #dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Pod
metadata:
  name: spgw
  labels:
    name: spgw-selector

spec:
  hostname: spgw
  #subdomain: spgw
  containers:
  - name: spgw
    image: cly1213/spgw:0.5
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /dev
        name: dev

      - mountPath: /usr/src
        name: src

      - mountPath: /lib/modules
        name: modules

  volumes:
  - name: dev
    hostPath:
      # directory location on host
      path: /dev
      # this field is optional
      #type: Directory
  - name: src
    hostPath:
      path: /usr/src

  - name: modules
    hostPath:
      path: /lib/modules

  #hostNetwork: true
  #restartPolicy: Always
  #dnsPolicy: ClusterFirst

  nodeSelector:
    labServer: "334"
---
apiVersion: v1
kind: Pod
metadata:
  name: enb
  labels:
    name: enb-selector

spec:
  hostname: enb
  #subdomain: enb
  containers:
  - name: enb
    image: cly1213/enb:0.5
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /dev
        name: dev

      - mountPath: /usr/src
        name: src

      - mountPath: /lib/modules
        name: modules

  volumes:
  - name: dev
    hostPath:
      # directory location on host
      path: /dev
      # this field is optional
      #type: Directory
  - name: src
    hostPath:
      path: /usr/src

  - name: modules
    hostPath:
      path: /lib/modules

  #hostNetwork: true
  #restartPolicy: Always
  #dnsPolicy: ClusterFirst

  nodeSelector:
    labServer: "334"
